// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/garaekz/goshort/url"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initURLAPI(db *gorm.DB) url.API {
	repository := url.ProvideRepository(db)
	service := url.ProvideService(repository)
	api := url.ProvideAPI(service)
	return api
}
